### ISSUE TITLE
Can you please update this tool to support the latest Forza Motorsports?

### ISSUE THREAD

**Issue by qq00qq00** [Juice-XIJ/forza_auto_gear#55]
Thx a lot.

**Comment by Juice-XIJ** [comment]
Hello @qq00qq00 , thanks for your reporting. I checked the submodule "forza_motorsport", which is already on the top of the latest commit "61845cb". The only different is my forked "forza_motorsport" has a few minor fixes. 

Let me know if you have any questions.

**Comment by qq00qq00** [comment]
Thx a lot，
I will test the latest version.
